### Foundational Machine Learning Concepts for Social Media Analytics

This notebook serves as a practical exploration of the fundamental algorithms and mathematical concepts that underpin the more complex models used in the main `twitter_analytics.ipynb` file. While the primary project focuses on sentiment analysis using deep learning, this notebook breaks down the core optimization and data manipulation techniques that are essential for any machine learning practitioner.

Here, we explore:
*   **Optimization Algorithms:** Such as the Genetic Algorithm and the Simplex method, which are foundational to understanding how models search for optimal solutions.
*   **Dynamic Programming:** Illustrated with the Knapsack problem, this showcases a powerful technique for solving complex problems by breaking them into smaller pieces.
*   **Linear Algebra with NumPy and Pandas:** A look at a look at matrix operations and vector mathematics, which are the building blocks of neural networks and data preprocessing pipelines.

Think of this notebook as a conceptual toolkit. The principles of optimization and data handling demonstrated here are directly applicable to the challenges of cleaning,processing, and modeling the unstructured text data found in tweets.

### Foundational Machine Learning Concepts for Social Media Analytics

This notebook serves as a practical exploration of the fundamental algorithms and mathematical concepts that underpin the more complex models used in the main `twitter_analytics.ipynb` file. While the primary project focuses on sentiment analysis using deep learning, this notebook breaks down the core optimization and data manipulation techniques that are essential for any machine learning practitioner.

Here, we explore:
*   **Optimization Algorithms:** Such as the Genetic Algorithm and the Simplex method, which are foundational to understanding how models search for optimal solutions.
*   **Dynamic Programming:** Illustrated with the Knapsack problem, this showcases a powerful technique for solving complex problems by breaking them into smaller pieces.
*   **Linear Algebra with NumPy and Pandas:** A look at matrix operations and vector mathematics, which are the building blocks of neural networks and data preprocessing pipelines.

Think of this notebook as a conceptual toolkit. The principles of optimization and data handling demonstrated here are directly applicable to the challenges of cleaning,processing, and modeling the unstructured text data found in tweets.

In [21]:
from numpy.random import randint
from numpy.random import rand
import pandas as pd

def onemax(x):
    return -sum(x)

def selection(pop, scores, k=3):
    selection_1 = randint(len(pop))
    for ix in randint(0, len(pop), k-1):
        if scores[ix] < scores[selection_1]:
            selection_1 = ix
    return pop[selection_1]
    
def crossover(p1, p2, r_cross):
    c1, c2 = p1.copy(), p2.copy()
    if rand() < r_cross:
        pt = randint(1, len(p1)-2)
        c1 = p1[:pt] + p2[pt:]
        c2 = p2[:pt] + p1[pt:]
    return [c1, c2]

def mutation(bitstring, r_mut):
    for i in range(len(bitstring)):
        if rand() < r_mut:
            bitstring[i] = 1 - bitstring[i]
            
def genetic_algorithm(objective, n_bits, n_iter, n_pop, r_cross, r_mut):
    pop = [randint(0,2,n_bits).tolist() for _ in range(n_pop)]
    best, best_eval = 0, objective(pop[0])
    for gen in range(n_iter):
        scores = [objective(c) for c in pop]
        for i in range(n_pop):
            if scores[i] < best_eval:
                best, best_eval = pop[i], scores[i]
                #print(">%d, new best f(%s) = %.3f" % (gen, pop[i], scores[i]))
        selected = [selection(pop, scores) for _ in range(n_pop)]
        children = list()
        for i in range(0, n_pop, 2):
            p1, p2 = selected[i], selected[i+1]
            for c in crossover(p1, p2, r_cross):
                mutation(c, r_mut)
                children.append(c)
        pop = children
    return [best, best_eval]

n_iter = 10
n_bits = 20
n_pop = 100
r_cross = 0.9
r_mut = 1.0 / float(n_bits)
best_list, score_list = [], []
for i in range(n_iter):
    best, score = genetic_algorithm(onemax, n_bits, n_iter, n_pop, r_cross, r_mut)
    best_list.append(best)
    score_list.append(score)
print('Done!')

results = pd.DataFrame({'best':best_list, 'score':score_list})
print(results)

Done!
                                                best  score
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
2  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
3  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
4  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
5  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
6  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
7  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
8  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20
9  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...    -20


### The Genetic Algorithm

The genetic algorithm is a global search optimization technique based on the principles of natural selection and biological evolution. In this program, we establish functions for the core evolutionary rules:

*   **Selection:** Selects the individuals, called "parents," that will contribute to the next generation.
*   **Crossover:** Combines two parents to form "children" for the next generation.
*   **Mutation:** Applies random changes to individual parents to introduce variation and form children.

I found this optimization algorithm to be the most suitable for the sentiment analysis aspect of my project. It is highly accurate, whereas other methods like simulated annealing can be too dependent on randomization.

#### Implementation Details

The algorithm begins by creating a random initial population. It then evaluates all candidates in the population and creates a sequence of new populations. A tournament selection procedure is implemented in the `selection` function, which takes the population and returns a chosen parent.

Next, we create the next generation using the `crossover` function. This function uses a random draw to determine if crossover occurs and then selects a valid split point. This randomization is key: `c1` and `c2` are the children created from parents `p1` and `p2` by splitting them at a random point `pt`.

The `mutation` function introduces further randomization by iterating through the bitstring and flipping bits based on a random chance (`r_mut`).

Finally, the algorithm proceeds to the next generation. It iterates through the population, selects parent pairs, performs crossover and mutation to create a list of children, and replaces the old population with this new generation. To test the algorithm, I used **OneMax**, an objective function that takes a bitstring and returns the negative sum of its values, guiding the algorithm to maximize the sum.

In [ ]:
import numpy as np
import pandas as pd
import math

mx = pd.DataFrame([[1,1,1], [0,1,2], [1,5,3]])

print(mx)
print(mx.values.diagonal())

n = 4
L = pd.DataFrame(np.tril(np.ones((n,n))), columns = range(n),
                 index = range(n))

U = pd.DataFrame(np.triu(np.ones((n,n))), columns = range(n),
                 index = range(n))

print(L)
print(U)

mx = pd.Series([[2,3]])

mag = mx.apply(lambda x: np.linalg.norm(x))
print(mag)

unitvector = mx.apply(lambda x: x/np.linalg.norm(x))
print(unitvector)

mx = pd.Series([5,12])

mag = mx.apply(lambda x: np.linalg.norm(x))
print(mag)

unitvector = mx.apply(lambda x: x/np.linalg.norm(x))
print(unitvector)

x = pd.Series([1,2,3,4,5])
y = pd.Series([5,6,7,8,9])

dimension = int(input("Enter the dimension of the identity matrix: "))
identity_matrix = pd.DataFrame(np.identity(dimension), 
                               columns = range(dimension), 
                               index = range(dimension))
print(identity_matrix)


print("Using the eye() function to create an identity matrix")
identity_matrix = pd.DataFrame(np.eye(3), columns = range(3), 
                               index = range(3))
print(identity_matrix)

   0  1  2
0  1  1  1
1  0  1  2
2  1  5  3
[1 1 3]
     0    1    2    3
0  1.0  0.0  0.0  0.0
1  1.0  1.0  0.0  0.0
2  1.0  1.0  1.0  0.0
3  1.0  1.0  1.0  1.0
     0    1    2    3
0  1.0  1.0  1.0  1.0
1  0.0  1.0  1.0  1.0
2  0.0  0.0  1.0  1.0
3  0.0  0.0  0.0  1.0
0    3.605551
dtype: float64
0    [0.5547001962252291, 0.8320502943378437]
dtype: object
0     5.0
1    12.0
dtype: float64
0    1.0
1    1.0
dtype: float64
Enter the dimension of the identity matrix: 4
     0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
Using the eye() function to create an identity matrix
     0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0


### Matrices: Magnitude, Unit Vectors, and Identity Matrices

I chose to explore matrices because I didn't fully understand their properties. I started by exploring NumPy's functions, such as `diagonal`, `tril` (lower-triangular), and `triu` (upper-triangular). I also created identity matrices using both `np.identity()` and `np.eye()`.

The most challenging concept was the **unit vector**. A unit vector doesn't represent magnitude; instead, it uses magnitude to find a purer representation of the original vector's direction. It tells you the direction where the data is most concentrated. For instance, the magnitude of a vector `[5, 12]` is calculated as `sqrt(5^2 + 12^2)`, which is 13. You would then divide each element of the vector by 13 to get the unit vector. This process isolates direction from length.

I used the `.apply()` function to perform these calculations in Pandas. While this was easier than implementing the genetic algorithm, it highlights how Pandas expands on NumPy's foundation. NumPy is excellent for structured numerical data, and Pandas enhances it with powerful tools for manipulating unstructured data.

In [4]:
import numpy as np
import scipy as sp
import pandas as pd

c= pd.Series([-8, -12, -22]).values
A= pd.DataFrame([[17, 27, 34], [12, 21, 15]]).values
b= pd.Series([91800, 42000]).values

R = (0, None)
T = (0, None)
M = (0, None)

from scipy.optimize import linprog

res = linprog(c, A_ub=A, b_ub=b, bounds=(R, T, M), method='simplex', options={"disp":True})
print(res)

Optimization terminated successfully.
         Current function value: -59400.000000
         Iterations: 3
     con: array([], dtype=float64)
     fun: -59400.0
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([   0., 1500.])
  status: 0
 success: True
       x: array([   0.,    0., 2700.])


### The Simplex Algorithm

The simplex algorithm is best described through analogy as this is the most user-friendly description. Imagine a stockbroker choosing between several stocks, like Tesla, Google, and Amazon. They have a finite amount of money and want to maximize their profit. The simplex algorithm helps solve this by improving an initial feasible solution until an optimal one is found.

The algorithm operates within a **feasible region**, which is like a map of all possible valid investment decisions. It starts at a corner of this region and moves to an adjacent corner that improves the **objective function** (in this case, maximizing profit). This process is repeated, moving from corner to corner, until no further improvement is possible.

This program uses SciPy's `linprog` function to find the optimal solution. The key parameters are:
*   `c`: The objective function, representing the potential profit from each stock.
*   `A_ub` and `b_ub`: The constraints, representing the limited resources (e.g., your savings and checking accounts).
*   `bounds`: Non-negativity constraints, ensuring the solution is realistic (you can't invest negative money).
*   `method='simplex'`: Specifies the algorithm to use.

In [9]:
import numpy as np
import pandas as pd

def knapsack(items, capacity):
    n = len(items)
    weight, value, num = zip(*items) # unpack items into separate lists for weight, value, and num
    weight = pd.Series(weight).values
    value = pd.Series(value).values
    dp = np.zeros((n+1, capacity+1))
    for i in range(1, n+1):
        dp[i, weight[i-1]:] = np.maximum(dp[i-1, weight[i-1]:], dp[i-1, :-weight[i-1]]+value[i-1])
        print(dp)
    return dp[n, capacity]

val = pd.DataFrame([(10, 50, 30), (70, 90, 180), (70, 250, 100)])
knapsack(val.values, 500)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ... 50. 50. 50.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...  50.  50.  50.]
 [  0.   0.   0. ... 140. 140. 140.]
 [  0.   0.   0. ...   0.   0.   0.]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...  50.  50.  50.]
 [  0.   0.   0. ... 140. 140. 140.]
 [  0.   0.   0. ... 390. 390. 390.]]


390.0

In [20]:
import pandas as pd

def knapsack(items, capacity):
    n = len(items)
    weight, value, num = zip(*items) # unpack items into separate lists for weight, value, and num
    weight = pd.Series(weight)
    value = pd.Series(value)
    dp = pd.DataFrame(0, index=range(n+1), columns=range(capacity+1))
    for i in range(1, n+1):
        padded_slice = np.pad(dp.iloc[i-1, :-weight[i-1]]+value[i-1], 
                              (weight[i-1], 0), 'constant', 
                              constant_values=(0))
        dp.iloc[i, :] = np.maximum(dp.iloc[i-1, :], padded_slice)
        print(dp)
    return dp.loc[n, capacity]

val = pd.DataFrame([(10, 50, 30), (70, 90, 180), (70, 250, 100)])
knapsack(val.values, 500)


3
   0    1    2    3    4    5    6    7    8    9    ...  491  492  493  494  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...   50   50   50   50   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   495  496  497  498  499  500  
0    0    0    0    0    0    0  
1   50   50   50   50   50   50  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  

[4 rows x 501 columns]
   0    1    2    3    4    5    6    7    8    9    ...  491  492  493  494  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...   50   50   50   50   
2    0    0    0    0    0    0    0    0    0    0  ...  140  140  140  140   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

  

390

### The Knapsack Problem with Dynamic Programming

I have another analogy for you! Imagine a thief breaks into a home with a knapsack. The home contains various items, each with its own weight and value. Jewelry might have high value but low weight, while a TV is heavy but less valuable. The thief's knapsack has a limited weight capacity, so they must choose the combination of items that maximizes their total value without exceeding the weight limit.

I used **dynamic programming** to solve this. This approach divides the main problem into smaller, overlapping subproblems. It solves each subproblem just once and stores the result, typically in a table, to avoid re-computation.

In this code, the DP table (`dp`) is constructed where rows represent the items available and columns represent the knapsack's capacity, from 0 to the maximum limit. The code iterates through each item and each possible weight, calculating the maximum value that can be achieved at each step. The final cell of the table contains the optimal total value.

For this implementation, I adapted the logic to work with Pandas DataFrames. A key step was using `np.pad` to ensure the matrix slices were the same size, which is required for the `np.maximum` function to compare the value of adding a new item versus keeping the previous best.